import { Inter } from "next/font/google";
import "./globals.css";
import BodyClassWrapper from "@/components/BodyClassWeapper";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],

});

export const metadata = {
  title: "Contravel App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <BodyClassWrapper>{children}</BodyClassWrapper>

      </body>
    </html>
  );
}
